[project]
name = "mcp-obsidian"
version = "0.1.0"
description = "MCP server for local Obsidian vault"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "llama-cpp-python>=0.3.8",
    "mcp[cli]>=1.6.0",
    "streamlit>=1.45.0",
]
